### ISSUE TITLE
방향키로 조작하기가 너무 불편합니다.

### ISSUE THREAD

**Issue by Yoon-SeokJin2** [seokjin1013/wizard-of-the-forest-3#1]
마우스는 보통 오른손으로 사용합니다. 이 게임은 마우스를 통해 공격을 하고 동시에 키보드로 캐릭터를 움직여야 하는 게임인데 그렇게 되면 왼손으로 방향키를 조작해야 합니다. 방향키가 키보드의 오른쪽에 있어 불편합니다. WASD로 움직일 수 있게 고려해주세요.

**Comment by seokjin1013** [comment]
좋은 의견입니다. 다음 커밋에서 반영하도록 하겠습니다.
